on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Golang install
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: Checkout
      uses: actions/checkout@v1

    - name: Test
      run: go test
